[debug] [2025-09-20T21:16:59.030Z] [Firebase Plugin] Activating Firebase extension.
[debug] [2025-09-20T21:17:11.466Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-09-20T21:17:11.469Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]
[debug] [2025-09-20T21:17:11.499Z] [Firebase Plugin] VSCode notification server listening on port 40001
[info] [Firebase Plugin] Starting Data Connect toolkit (version 2.13.0) on port 50001
[info] i  dataconnect: downloading dataconnect-emulator-2.13.0... {"metadata":{"emulator":{"name":"dataconnect"},"message":"downloading dataconnect-emulator-2.13.0..."}}
[debug] [2025-09-20T21:17:13.932Z] >>> [apiv2][query] GET https://storage.googleapis.com/firemat-preview-drop/emulator/dataconnect-emulator-linux-v2.13.0 
[debug] [2025-09-20T21:17:14.358Z] <<< [apiv2][status] GET https://storage.googleapis.com/firemat-preview-drop/emulator/dataconnect-emulator-linux-v2.13.0 200
[debug] [2025-09-20T21:17:14.366Z] <<< [apiv2][body] GET https://storage.googleapis.com/firemat-preview-drop/emulator/dataconnect-emulator-linux-v2.13.0 [stream]
[debug] [2025-09-20T21:17:16.435Z] 'fdc build' failed with error: Unable to build your Data Connect schema and connectors (exit code 1): E0920 21:17:16.432069   14987 cmd.go:43] Error loading data connect config: could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"'fdc build' failed with error: Unable to build your Data Connect schema and connectors (exit code 1): E0920 21:17:16.432069   14987 cmd.go:43] Error loading data connect config: could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:17:16.439Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2025-09-20T21:17:16.439Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: port"}}
[debug] [2025-09-20T21:17:16.440Z] Starting Data Connect Emulator with command {"binary":"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0","args":["--logtostderr","-v=2","dev","--listen=localhost:50001","--config_dir=/home/user/studio/dataconnect","--enable_output_schema_extensions=true","--enable_output_generated_sdk=true"],"optionalArgs":["listen","config_dir","enable_output_schema_extensions","enable_output_generated_sdk"],"joinArgs":true,"shell":false,"port":9399} {"metadata":{"emulator":{"name":"dataconnect"},"message":"Starting Data Connect Emulator with command {\"binary\":\"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0\",\"args\":[\"--logtostderr\",\"-v=2\",\"dev\",\"--listen=localhost:50001\",\"--config_dir=/home/user/studio/dataconnect\",\"--enable_output_schema_extensions=true\",\"--enable_output_generated_sdk=true\"],\"optionalArgs\":[\"listen\",\"config_dir\",\"enable_output_schema_extensions\",\"enable_output_generated_sdk\"],\"joinArgs\":true,\"shell\":false,\"port\":9399}"}}
[info] i  dataconnect: Data Connect Emulator logging to dataconnect-debug.log {"metadata":{"emulator":{"name":"dataconnect"},"message":"Data Connect Emulator logging to dataconnect-debug.log"}}
[debug] [2025-09-20T21:17:16.501Z] E0920 21:17:16.500983   14992 dev.go:79] Failed to load initial config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:17:16.500983   14992 dev.go:79] Failed to load initial config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:17:16.509Z] E0920 21:17:16.502233   14992 watch.go:102] watchAllDir unable to walk dir `/home/user/studio/dataconnect`: lstat /home/user/studio/dataconnect: no such file or directory
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:17:16.502233   14992 watch.go:102] watchAllDir unable to walk dir `/home/user/studio/dataconnect`: lstat /home/user/studio/dataconnect: no such file or directory\n"}}
[debug] [2025-09-20T21:17:16.529Z] I0920 21:17:16.527979   14992 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 21:17:16.527979   14992 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001\n"}}
[error] [Firebase Plugin] error:  {}
[debug] [2025-09-20T21:17:26.507Z] E0920 21:17:26.506017   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:17:26.506017   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:17:36.503Z] E0920 21:17:36.502706   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:17:36.502706   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:17:46.503Z] E0920 21:17:46.503049   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:17:46.503049   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:17:50.408Z] Running auto auth
[debug] [2025-09-20T21:17:50.460Z] No OAuth tokens found
[debug] [2025-09-20T21:17:50.466Z] [Firebase Plugin] User found:  innovativeenterprisesoman@gmail.com
[info] [Firebase Plugin] (Core:Project) New user detected, fetching projects
[debug] [2025-09-20T21:17:50.474Z] No OAuth tokens found
[debug] [2025-09-20T21:17:50.482Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2025-09-20T21:17:51.275Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects 200
[debug] [2025-09-20T21:17:51.279Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects [omitted]
[debug] [2025-09-20T21:17:56.514Z] E0920 21:17:56.514033   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:17:56.514033   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:18:06.513Z] E0920 21:18:06.512028   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:18:06.512028   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:18:16.504Z] E0920 21:18:16.503269   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:18:16.503269   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:18:26.514Z] E0920 21:18:26.512160   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:18:26.512160   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:18:36.511Z] E0920 21:18:36.511058   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:18:36.511058   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:18:46.503Z] E0920 21:18:46.503430   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:18:46.503430   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:18:56.510Z] E0920 21:18:56.507802   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:18:56.507802   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:18:58.645Z] [Firebase Plugin] Value of process.env.MONOSPACE_ENV: true
[debug] [2025-09-20T21:18:58.646Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-09-20T21:18:58.647Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]
[debug] [2025-09-20T21:18:58.648Z] > authorizing via signed-in user (innovativeenterprisesoman@gmail.com)
[debug] [2025-09-20T21:18:58.650Z] [Firebase Plugin] Value of process.env.MONOSPACE_ENV: true
[debug] [2025-09-20T21:18:58.651Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-09-20T21:18:58.652Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]
[debug] [2025-09-20T21:18:58.652Z] > authorizing via signed-in user (innovativeenterprisesoman@gmail.com)
[debug] [2025-09-20T21:18:58.653Z] Emulator locator file path: /tmp/hub-innovative-enterprises.json
[debug] [2025-09-20T21:18:58.656Z] No OAuth tokens found
[debug] [2025-09-20T21:18:58.656Z] No OAuth tokens found
[debug] [2025-09-20T21:18:58.656Z] [Firebase Plugin] User found:  innovativeenterprisesoman@gmail.com
[debug] [2025-09-20T21:18:58.657Z] [Firebase Plugin] User found:  innovativeenterprisesoman@gmail.com
[info] [Firebase Plugin] (Core:Project) New user detected, fetching projects
[debug] [2025-09-20T21:18:58.658Z] No OAuth tokens found
[info] [Firebase Plugin] (Core:Project) New user detected, fetching projects
[debug] [2025-09-20T21:18:58.659Z] No OAuth tokens found
[debug] [2025-09-20T21:18:58.660Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2025-09-20T21:18:58.663Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2025-09-20T21:18:59.154Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects 200
[debug] [2025-09-20T21:18:59.158Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects [omitted]
[debug] [2025-09-20T21:18:59.164Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects 200
[debug] [2025-09-20T21:18:59.167Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects [omitted]
[debug] [2025-09-20T21:19:06.511Z] E0920 21:19:06.511182   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:19:06.511182   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:19:16.506Z] E0920 21:19:16.503250   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
E0920 21:19:16.503315   14992 watch.go:102] watchAllDir unable to walk dir `/home/user/studio/dataconnect`: lstat /home/user/studio/dataconnect: no such file or directory
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:19:16.503250   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\nE0920 21:19:16.503315   14992 watch.go:102] watchAllDir unable to walk dir `/home/user/studio/dataconnect`: lstat /home/user/studio/dataconnect: no such file or directory\n"}}
[debug] [2025-09-20T21:19:26.503Z] E0920 21:19:26.503200   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:19:26.503200   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:19:36.512Z] E0920 21:19:36.512135   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:19:36.512135   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:19:46.504Z] E0920 21:19:46.503556   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:19:46.503556   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:19:56.513Z] E0920 21:19:56.513050   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:19:56.513050   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:20:06.508Z] E0920 21:20:06.508157   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:20:06.508157   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:20:16.503Z] E0920 21:20:16.503504   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:20:16.503504   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:20:26.507Z] E0920 21:20:26.507149   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:20:26.507149   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:20:36.502Z] E0920 21:20:36.502647   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:20:36.502647   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:20:46.503Z] E0920 21:20:46.503366   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:20:46.503366   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:20:56.502Z] E0920 21:20:56.502648   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:20:56.502648   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:21:06.503Z] E0920 21:21:06.502662   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:21:06.502662   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:21:16.503Z] E0920 21:21:16.503043   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:21:16.503043   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:21:16.504Z] E0920 21:21:16.503096   14992 watch.go:102] watchAllDir unable to walk dir `/home/user/studio/dataconnect`: lstat /home/user/studio/dataconnect: no such file or directory
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:21:16.503096   14992 watch.go:102] watchAllDir unable to walk dir `/home/user/studio/dataconnect`: lstat /home/user/studio/dataconnect: no such file or directory\n"}}
[debug] [2025-09-20T21:21:26.508Z] E0920 21:21:26.508419   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:21:26.508419   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:21:36.503Z] E0920 21:21:36.503047   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:21:36.503047   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:21:46.503Z] E0920 21:21:46.503087   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:21:46.503087   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:21:56.507Z] E0920 21:21:56.507156   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:21:56.507156   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:22:06.508Z] E0920 21:22:06.508116   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:22:06.508116   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:22:16.502Z] E0920 21:22:16.502504   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:22:16.502504   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:22:26.503Z] E0920 21:22:26.502678   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:22:26.502678   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:22:36.513Z] E0920 21:22:36.513014   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:22:36.513014   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:22:46.503Z] E0920 21:22:46.503337   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:22:46.503337   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:22:56.511Z] E0920 21:22:56.511097   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:22:56.511097   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:23:06.512Z] E0920 21:23:06.512040   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:23:06.512040   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:23:16.504Z] E0920 21:23:16.504017   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
E0920 21:23:16.504072   14992 watch.go:102] watchAllDir unable to walk dir `/home/user/studio/dataconnect`: lstat /home/user/studio/dataconnect: no such file or directory
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:23:16.504017   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\nE0920 21:23:16.504072   14992 watch.go:102] watchAllDir unable to walk dir `/home/user/studio/dataconnect`: lstat /home/user/studio/dataconnect: no such file or directory\n"}}
[debug] [2025-09-20T21:23:26.512Z] E0920 21:23:26.512134   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:23:26.512134   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:23:36.512Z] E0920 21:23:36.512054   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:23:36.512054   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:23:46.503Z] E0920 21:23:46.502873   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:23:46.502873   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:23:56.503Z] E0920 21:23:56.502758   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:23:56.502758   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:24:06.512Z] E0920 21:24:06.512286   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:24:06.512286   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:24:16.503Z] E0920 21:24:16.503403   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:24:16.503403   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:24:26.503Z] E0920 21:24:26.503253   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:24:26.503253   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:24:36.514Z] E0920 21:24:36.512637   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:24:36.512637   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:24:46.503Z] E0920 21:24:46.503288   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:24:46.503288   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:24:56.512Z] E0920 21:24:56.512075   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:24:56.512075   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:25:06.513Z] E0920 21:25:06.513273   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:25:06.513273   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:25:16.502Z] E0920 21:25:16.502465   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
E0920 21:25:16.502522   14992 watch.go:102] watchAllDir unable to walk dir `/home/user/studio/dataconnect`: lstat /home/user/studio/dataconnect: no such file or directory
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:25:16.502465   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\nE0920 21:25:16.502522   14992 watch.go:102] watchAllDir unable to walk dir `/home/user/studio/dataconnect`: lstat /home/user/studio/dataconnect: no such file or directory\n"}}
[debug] [2025-09-20T21:25:26.513Z] E0920 21:25:26.511034   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:25:26.511034   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:25:36.513Z] E0920 21:25:36.512583   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:25:36.512583   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:25:46.503Z] E0920 21:25:46.503079   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:25:46.503079   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:25:56.502Z] E0920 21:25:56.502672   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:25:56.502672   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:26:06.514Z] E0920 21:26:06.514052   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:26:06.514052   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:26:16.503Z] E0920 21:26:16.502970   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:26:16.502970   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:26:26.512Z] E0920 21:26:26.512002   14992 watch.go:31] Failed to load config from "/home/user/studio/dataconnect": could not find dataconnect.yaml in `/home/user/studio/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:26:26.512002   14992 watch.go:31] Failed to load config from \"/home/user/studio/dataconnect\": could not find dataconnect.yaml in `/home/user/studio/dataconnect`\n"}}
[debug] [2025-09-20T21:26:36.516Z] I0920 21:26:36.513741   14992 load.go:31] Reloading schema and connectors...
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 21:26:36.513741   14992 load.go:31] Reloading schema and connectors...\n"}}
[debug] [2025-09-20T21:26:37.010Z] W0920 21:26:37.004397   14992 control.go:68] [/emulator/studio 373f] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0920 21:26:37.008082   14992 control.go:94] [/emulator/studio 373f] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0920 21:26:37.004397   14992 control.go:68] [/emulator/studio 373f] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0920 21:26:37.008082   14992 control.go:94] [/emulator/studio 373f] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \n"}}
[debug] [2025-09-20T21:26:37.017Z] E0920 21:26:37.017095   14992 load.go:73] Could not load sources: 
Errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 21:26:37.017095   14992 load.go:73] Could not load sources: \nErrors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n"}}
[debug] [2025-09-20T21:26:37.026Z] I0920 21:26:37.019880   14992 collector.go:107] schema extensions wrote into "/home/user/studio/dataconnect/.dataconnect/schema"
Generated sources: main/input.gql [68752B] main/relation.gql [33941B] prelude.gql [73251B] main/query.gql [7604B] main/mutation.gql [20515B] main/implicit.gql [3592B] 
I0920 21:26:37.024056   14992 load.go:74] Finished reloading
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 21:26:37.019880   14992 collector.go:107] schema extensions wrote into \"/home/user/studio/dataconnect/.dataconnect/schema\"\nGenerated sources: main/input.gql [68752B] main/relation.gql [33941B] prelude.gql [73251B] main/query.gql [7604B] main/mutation.gql [20515B] main/implicit.gql [3592B] \nI0920 21:26:37.024056   14992 load.go:74] Finished reloading\n"}}
[info] [Firebase Plugin] Stopping Data Connect toolkit
[warn] ⚠  Data Connect Emulator has exited upon receiving signal: SIGINT 
[debug] [2025-09-20T22:10:33.697Z] [Firebase Plugin] Activating Firebase extension.
[debug] [2025-09-20T22:11:00.992Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-09-20T22:11:00.995Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]
[debug] [2025-09-20T22:11:01.015Z] [Firebase Plugin] VSCode notification server listening on port 40001
[info] [Firebase Plugin] Starting Data Connect toolkit (version 2.13.0) on port 50001
[debug] [2025-09-20T22:11:08.009Z] W0920 22:11:07.971772   18781 control.go:68] [/emulator/studio 67be] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0920 22:11:08.006034   18781 control.go:94] [/emulator/studio 67be] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0920 22:11:07.971772   18781 control.go:68] [/emulator/studio 67be] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0920 22:11:08.006034   18781 control.go:94] [/emulator/studio 67be] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \n"}}
[debug] [2025-09-20T22:11:08.012Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2025-09-20T22:11:08.012Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: port"}}
[debug] [2025-09-20T22:11:08.013Z] Starting Data Connect Emulator with command {"binary":"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0","args":["--logtostderr","-v=2","dev","--listen=localhost:50001","--config_dir=/home/user/studio/dataconnect","--enable_output_schema_extensions=true","--enable_output_generated_sdk=true"],"optionalArgs":["listen","config_dir","enable_output_schema_extensions","enable_output_generated_sdk"],"joinArgs":true,"shell":false,"port":9399} {"metadata":{"emulator":{"name":"dataconnect"},"message":"Starting Data Connect Emulator with command {\"binary\":\"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0\",\"args\":[\"--logtostderr\",\"-v=2\",\"dev\",\"--listen=localhost:50001\",\"--config_dir=/home/user/studio/dataconnect\",\"--enable_output_schema_extensions=true\",\"--enable_output_generated_sdk=true\"],\"optionalArgs\":[\"listen\",\"config_dir\",\"enable_output_schema_extensions\",\"enable_output_generated_sdk\"],\"joinArgs\":true,\"shell\":false,\"port\":9399}"}}
[info] i  dataconnect: Data Connect Emulator logging to dataconnect-debug.log {"metadata":{"emulator":{"name":"dataconnect"},"message":"Data Connect Emulator logging to dataconnect-debug.log"}}
[error] [Firebase Plugin] requireAuth error: Could not refresh access token: Unsuccessful response status code. Request failed with status code 500
[debug] [2025-09-20T22:11:09.001Z] I0920 22:11:08.133822   18787 load.go:31] Reloading schema and connectors...
W0920 22:11:08.471823   18787 control.go:68] [/emulator/studio bab8] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0920 22:11:08.471925   18787 control.go:94] [/emulator/studio bab8] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
E0920 22:11:08.481228   18787 load.go:73] Could not load sources: 
Errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data
I0920 22:11:08.483144   18787 collector.go:107] schema extensions wrote into "/home/user/studio/dataconnect/.dataconnect/schema"
Generated sources: prelude.gql [73251B] main/implicit.gql [3592B] main/input.gql [68752B] main/relation.gql [33941B] main/query.gql [7604B] main/mutation.gql [20515B] 
I0920 22:11:08.483196   18787 load.go:74] Finished reloading
I0920 22:11:08.620891   18787 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 22:11:08.133822   18787 load.go:31] Reloading schema and connectors...\nW0920 22:11:08.471823   18787 control.go:68] [/emulator/studio bab8] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0920 22:11:08.471925   18787 control.go:94] [/emulator/studio bab8] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \nE0920 22:11:08.481228   18787 load.go:73] Could not load sources: \nErrors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\nI0920 22:11:08.483144   18787 collector.go:107] schema extensions wrote into \"/home/user/studio/dataconnect/.dataconnect/schema\"\nGenerated sources: prelude.gql [73251B] main/implicit.gql [3592B] main/input.gql [68752B] main/relation.gql [33941B] main/query.gql [7604B] main/mutation.gql [20515B] \nI0920 22:11:08.483196   18787 load.go:74] Finished reloading\nI0920 22:11:08.620891   18787 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001\n"}}
[debug] [2025-09-20T22:11:09.481Z] I0920 22:11:09.481071   18787 engine.go:169] [/emulator/studio bab8] ExecuteGraphqlRead IntrospectionQuery: succeeded. 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 22:11:09.481071   18787 engine.go:169] [/emulator/studio bab8] ExecuteGraphqlRead IntrospectionQuery: succeeded. \n"}}
[info] [Firebase Plugin] Stopping Data Connect toolkit
[warn] ⚠  Data Connect Emulator has exited upon receiving signal: SIGINT 
[debug] [2025-09-20T22:30:02.967Z] [Firebase Plugin] Activating Firebase extension.
[debug] [2025-09-20T22:30:11.832Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-09-20T22:30:11.834Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]
[debug] [2025-09-20T22:30:11.900Z] [Firebase Plugin] VSCode notification server listening on port 40001
[info] [Firebase Plugin] Starting Data Connect toolkit (version 2.13.0) on port 50001
[debug] [2025-09-20T22:30:17.309Z] W0920 22:30:17.298379   20418 control.go:68] [/emulator/studio f33f] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0920 22:30:17.298550   20418 control.go:94] [/emulator/studio f33f] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0920 22:30:17.298379   20418 control.go:68] [/emulator/studio f33f] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0920 22:30:17.298550   20418 control.go:94] [/emulator/studio f33f] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \n"}}
[debug] [2025-09-20T22:30:17.317Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2025-09-20T22:30:17.320Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: port"}}
[debug] [2025-09-20T22:30:17.321Z] Starting Data Connect Emulator with command {"binary":"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0","args":["--logtostderr","-v=2","dev","--listen=localhost:50001","--config_dir=/home/user/studio/dataconnect","--enable_output_schema_extensions=true","--enable_output_generated_sdk=true"],"optionalArgs":["listen","config_dir","enable_output_schema_extensions","enable_output_generated_sdk"],"joinArgs":true,"shell":false,"port":9399} {"metadata":{"emulator":{"name":"dataconnect"},"message":"Starting Data Connect Emulator with command {\"binary\":\"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0\",\"args\":[\"--logtostderr\",\"-v=2\",\"dev\",\"--listen=localhost:50001\",\"--config_dir=/home/user/studio/dataconnect\",\"--enable_output_schema_extensions=true\",\"--enable_output_generated_sdk=true\"],\"optionalArgs\":[\"listen\",\"config_dir\",\"enable_output_schema_extensions\",\"enable_output_generated_sdk\"],\"joinArgs\":true,\"shell\":false,\"port\":9399}"}}
[info] i  dataconnect: Data Connect Emulator logging to dataconnect-debug.log {"metadata":{"emulator":{"name":"dataconnect"},"message":"Data Connect Emulator logging to dataconnect-debug.log"}}
[debug] [2025-09-20T22:30:17.620Z] I0920 22:30:17.490834   20423 load.go:31] Reloading schema and connectors...
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 22:30:17.490834   20423 load.go:31] Reloading schema and connectors...\n"}}
[debug] [2025-09-20T22:30:17.937Z] W0920 22:30:17.837087   20423 control.go:68] [/emulator/studio 0fbf] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0920 22:30:17.837161   20423 control.go:94] [/emulator/studio 0fbf] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
E0920 22:30:17.842078   20423 load.go:73] Could not load sources: 
Errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data
I0920 22:30:17.846247   20423 collector.go:107] schema extensions wrote into "/home/user/studio/dataconnect/.dataconnect/schema"
Generated sources: prelude.gql [73251B] main/query.gql [7604B] main/mutation.gql [20515B] main/implicit.gql [3592B] main/input.gql [68752B] main/relation.gql [33941B] 
I0920 22:30:17.848226   20423 load.go:74] Finished reloading
I0920 22:30:17.911486   20423 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0920 22:30:17.837087   20423 control.go:68] [/emulator/studio 0fbf] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0920 22:30:17.837161   20423 control.go:94] [/emulator/studio 0fbf] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \nE0920 22:30:17.842078   20423 load.go:73] Could not load sources: \nErrors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\nI0920 22:30:17.846247   20423 collector.go:107] schema extensions wrote into \"/home/user/studio/dataconnect/.dataconnect/schema\"\nGenerated sources: prelude.gql [73251B] main/query.gql [7604B] main/mutation.gql [20515B] main/implicit.gql [3592B] main/input.gql [68752B] main/relation.gql [33941B] \nI0920 22:30:17.848226   20423 load.go:74] Finished reloading\nI0920 22:30:17.911486   20423 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001\n"}}
[debug] [2025-09-20T22:30:19.827Z] I0920 22:30:19.165697   20423 engine.go:169] [/emulator/studio 0fbf] ExecuteGraphqlRead IntrospectionQuery: succeeded. 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 22:30:19.165697   20423 engine.go:169] [/emulator/studio 0fbf] ExecuteGraphqlRead IntrospectionQuery: succeeded. \n"}}
[debug] [2025-09-20T22:30:37.059Z] Running auto auth
[debug] [2025-09-20T22:30:37.478Z] No OAuth tokens found
[debug] [2025-09-20T22:30:37.482Z] [Firebase Plugin] User found:  innovativeenterprisesoman@gmail.com
[info] [Firebase Plugin] (Core:Project) New user detected, fetching projects
[debug] [2025-09-20T22:30:37.486Z] No OAuth tokens found
[debug] [2025-09-20T22:30:37.499Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2025-09-20T22:30:38.279Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects 200
[debug] [2025-09-20T22:30:38.281Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects [omitted]
[info] [Firebase Plugin] Stopping Data Connect toolkit
[warn] ⚠  Data Connect Emulator has exited upon receiving signal: SIGINT 
[debug] [2025-09-20T22:45:34.470Z] [Firebase Plugin] Activating Firebase extension.
[debug] [2025-09-20T22:46:01.626Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-09-20T22:46:01.630Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]
[debug] [2025-09-20T22:46:01.632Z] > authorizing via signed-in user (innovativeenterprisesoman@gmail.com)
[debug] [2025-09-20T22:46:01.644Z] No OAuth tokens found
[debug] [2025-09-20T22:46:01.646Z] No OAuth tokens found
[debug] [2025-09-20T22:46:01.648Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]
[debug] [2025-09-20T22:46:01.649Z] > authorizing via signed-in user (innovativeenterprisesoman@gmail.com)
[debug] [2025-09-20T22:46:01.650Z] [Firebase Plugin] User found:  innovativeenterprisesoman@gmail.com
[info] [Firebase Plugin] (Core:Project) New user detected, fetching projects
[debug] [2025-09-20T22:46:01.657Z] No OAuth tokens found
[debug] [2025-09-20T22:46:01.662Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2025-09-20T22:46:01.775Z] [Firebase Plugin] VSCode notification server listening on port 40001
[debug] [2025-09-20T22:46:03.473Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects 200
[debug] [2025-09-20T22:46:03.474Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects [omitted]
[info] [Firebase Plugin] Starting Data Connect toolkit (version 2.13.0) on port 50001
[debug] [2025-09-20T22:46:06.263Z] W0920 22:46:06.258927   23940 control.go:68] [/emulator/studio e2c9] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0920 22:46:06.259074   23940 control.go:94] [/emulator/studio e2c9] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0920 22:46:06.258927   23940 control.go:68] [/emulator/studio e2c9] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0920 22:46:06.259074   23940 control.go:94] [/emulator/studio e2c9] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \n"}}
[debug] [2025-09-20T22:46:06.265Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2025-09-20T22:46:06.266Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: port"}}
[debug] [2025-09-20T22:46:06.267Z] Starting Data Connect Emulator with command {"binary":"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0","args":["--logtostderr","-v=2","dev","--listen=localhost:50001","--config_dir=/home/user/studio/dataconnect","--enable_output_schema_extensions=true","--enable_output_generated_sdk=true"],"optionalArgs":["listen","config_dir","enable_output_schema_extensions","enable_output_generated_sdk"],"joinArgs":true,"shell":false,"port":9399} {"metadata":{"emulator":{"name":"dataconnect"},"message":"Starting Data Connect Emulator with command {\"binary\":\"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0\",\"args\":[\"--logtostderr\",\"-v=2\",\"dev\",\"--listen=localhost:50001\",\"--config_dir=/home/user/studio/dataconnect\",\"--enable_output_schema_extensions=true\",\"--enable_output_generated_sdk=true\"],\"optionalArgs\":[\"listen\",\"config_dir\",\"enable_output_schema_extensions\",\"enable_output_generated_sdk\"],\"joinArgs\":true,\"shell\":false,\"port\":9399}"}}
[info] i  dataconnect: Data Connect Emulator logging to dataconnect-debug.log {"metadata":{"emulator":{"name":"dataconnect"},"message":"Data Connect Emulator logging to dataconnect-debug.log"}}
[debug] [2025-09-20T22:46:06.395Z] I0920 22:46:06.382745   23945 load.go:31] Reloading schema and connectors...
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 22:46:06.382745   23945 load.go:31] Reloading schema and connectors...\n"}}
[debug] [2025-09-20T22:46:06.636Z] W0920 22:46:06.635769   23945 control.go:68] [/emulator/studio b0b5] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0920 22:46:06.635848   23945 control.go:94] [/emulator/studio b0b5] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0920 22:46:06.635769   23945 control.go:68] [/emulator/studio b0b5] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0920 22:46:06.635848   23945 control.go:94] [/emulator/studio b0b5] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \n"}}
[debug] [2025-09-20T22:46:06.648Z] E0920 22:46:06.647444   23945 load.go:73] Could not load sources: 
Errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0920 22:46:06.647444   23945 load.go:73] Could not load sources: \nErrors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n"}}
[debug] [2025-09-20T22:46:06.661Z] I0920 22:46:06.658281   23945 collector.go:107] schema extensions wrote into "/home/user/studio/dataconnect/.dataconnect/schema"
Generated sources: main/input.gql [68752B] main/relation.gql [33941B] main/query.gql [7604B] main/mutation.gql [20515B] prelude.gql [73251B] main/implicit.gql [3592B] 
I0920 22:46:06.658351   23945 load.go:74] Finished reloading
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 22:46:06.658281   23945 collector.go:107] schema extensions wrote into \"/home/user/studio/dataconnect/.dataconnect/schema\"\nGenerated sources: main/input.gql [68752B] main/relation.gql [33941B] main/query.gql [7604B] main/mutation.gql [20515B] prelude.gql [73251B] main/implicit.gql [3592B] \nI0920 22:46:06.658351   23945 load.go:74] Finished reloading\n"}}
[debug] [2025-09-20T22:46:06.675Z] I0920 22:46:06.673763   23945 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 22:46:06.673763   23945 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001\n"}}
[debug] [2025-09-20T22:46:06.890Z] I0920 22:46:06.889515   23945 engine.go:169] [/emulator/studio b0b5] ExecuteGraphqlRead IntrospectionQuery: succeeded. 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 22:46:06.889515   23945 engine.go:169] [/emulator/studio b0b5] ExecuteGraphqlRead IntrospectionQuery: succeeded. \n"}}
[info] [Firebase Plugin] Stopping Data Connect toolkit
[warn] ⚠  Data Connect Emulator has exited upon receiving signal: SIGINT 
[debug] [2025-09-20T23:15:49.032Z] [Firebase Plugin] Activating Firebase extension.
[debug] [2025-09-20T23:16:43.553Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-09-20T23:16:43.561Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]
[debug] [2025-09-20T23:16:43.648Z] [Firebase Plugin] VSCode notification server listening on port 40001
[info] [Firebase Plugin] Starting Data Connect toolkit (version 2.13.0) on port 50001
[debug] [2025-09-20T23:16:48.275Z] W0920 23:16:48.258155   30322 control.go:68] [/emulator/studio 2951] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0920 23:16:48.261626   30322 control.go:94] [/emulator/studio 2951] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0920 23:16:48.258155   30322 control.go:68] [/emulator/studio 2951] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0920 23:16:48.261626   30322 control.go:94] [/emulator/studio 2951] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \n"}}
[debug] [2025-09-20T23:16:48.283Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2025-09-20T23:16:48.284Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: port"}}
[debug] [2025-09-20T23:16:48.288Z] Starting Data Connect Emulator with command {"binary":"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0","args":["--logtostderr","-v=2","dev","--listen=localhost:50001","--config_dir=/home/user/studio/dataconnect","--enable_output_schema_extensions=true","--enable_output_generated_sdk=true"],"optionalArgs":["listen","config_dir","enable_output_schema_extensions","enable_output_generated_sdk"],"joinArgs":true,"shell":false,"port":9399} {"metadata":{"emulator":{"name":"dataconnect"},"message":"Starting Data Connect Emulator with command {\"binary\":\"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0\",\"args\":[\"--logtostderr\",\"-v=2\",\"dev\",\"--listen=localhost:50001\",\"--config_dir=/home/user/studio/dataconnect\",\"--enable_output_schema_extensions=true\",\"--enable_output_generated_sdk=true\"],\"optionalArgs\":[\"listen\",\"config_dir\",\"enable_output_schema_extensions\",\"enable_output_generated_sdk\"],\"joinArgs\":true,\"shell\":false,\"port\":9399}"}}
[info] i  dataconnect: Data Connect Emulator logging to dataconnect-debug.log {"metadata":{"emulator":{"name":"dataconnect"},"message":"Data Connect Emulator logging to dataconnect-debug.log"}}
[debug] [2025-09-20T23:16:48.533Z] I0920 23:16:48.430105   30328 load.go:31] Reloading schema and connectors...
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 23:16:48.430105   30328 load.go:31] Reloading schema and connectors...\n"}}
[debug] [2025-09-20T23:16:48.947Z] W0920 23:16:48.832173   30328 control.go:68] [/emulator/studio cb6a] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0920 23:16:48.832261   30328 control.go:94] [/emulator/studio cb6a] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
E0920 23:16:48.858322   30328 load.go:73] Could not load sources: 
Errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data
I0920 23:16:48.879580   30328 collector.go:107] schema extensions wrote into "/home/user/studio/dataconnect/.dataconnect/schema"
Generated sources: prelude.gql [73251B] main/implicit.gql [3592B] main/input.gql [68752B] main/relation.gql [33941B] main/query.gql [7604B] main/mutation.gql [20515B] 
I0920 23:16:48.879657   30328 load.go:74] Finished reloading
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0920 23:16:48.832173   30328 control.go:68] [/emulator/studio cb6a] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0920 23:16:48.832261   30328 control.go:94] [/emulator/studio cb6a] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \nE0920 23:16:48.858322   30328 load.go:73] Could not load sources: \nErrors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\nI0920 23:16:48.879580   30328 collector.go:107] schema extensions wrote into \"/home/user/studio/dataconnect/.dataconnect/schema\"\nGenerated sources: prelude.gql [73251B] main/implicit.gql [3592B] main/input.gql [68752B] main/relation.gql [33941B] main/query.gql [7604B] main/mutation.gql [20515B] \nI0920 23:16:48.879657   30328 load.go:74] Finished reloading\n"}}
[debug] [2025-09-20T23:16:48.991Z] I0920 23:16:48.949505   30328 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 23:16:48.949505   30328 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001\n"}}
[debug] [2025-09-20T23:16:49.510Z] I0920 23:16:49.510028   30328 engine.go:169] [/emulator/studio cb6a] ExecuteGraphqlRead IntrospectionQuery: succeeded. 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0920 23:16:49.510028   30328 engine.go:169] [/emulator/studio cb6a] ExecuteGraphqlRead IntrospectionQuery: succeeded. \n"}}
[debug] [2025-09-20T23:17:11.020Z] Running auto auth
[debug] [2025-09-20T23:17:11.087Z] No OAuth tokens found
[debug] [2025-09-20T23:17:11.089Z] [Firebase Plugin] User found:  innovativeenterprisesoman@gmail.com
[info] [Firebase Plugin] (Core:Project) New user detected, fetching projects
[debug] [2025-09-20T23:17:11.095Z] No OAuth tokens found
[debug] [2025-09-20T23:17:11.101Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2025-09-20T23:17:11.702Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects 200
[debug] [2025-09-20T23:17:11.703Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects [omitted]
[info] [Firebase Plugin] Stopping Data Connect toolkit
[warn] ⚠  Data Connect Emulator has exited upon receiving signal: SIGINT 
[debug] [2025-09-21T02:19:16.576Z] [Firebase Plugin] Activating Firebase extension.
[debug] [2025-09-21T02:20:21.232Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-09-21T02:20:21.249Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]
[debug] [2025-09-21T02:20:21.346Z] [Firebase Plugin] VSCode notification server listening on port 40001
[info] [Firebase Plugin] Starting Data Connect toolkit (version 2.13.0) on port 50001
[debug] [2025-09-21T02:20:32.725Z] W0921 02:20:32.720878   33077 control.go:68] [/emulator/studio 4679] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0921 02:20:32.721255   33077 control.go:94] [/emulator/studio 4679] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0921 02:20:32.720878   33077 control.go:68] [/emulator/studio 4679] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0921 02:20:32.721255   33077 control.go:94] [/emulator/studio 4679] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \n"}}
[debug] [2025-09-21T02:20:32.729Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2025-09-21T02:20:32.729Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: port"}}
[debug] [2025-09-21T02:20:32.730Z] Starting Data Connect Emulator with command {"binary":"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0","args":["--logtostderr","-v=2","dev","--listen=localhost:50001","--config_dir=/home/user/studio/dataconnect","--enable_output_schema_extensions=true","--enable_output_generated_sdk=true"],"optionalArgs":["listen","config_dir","enable_output_schema_extensions","enable_output_generated_sdk"],"joinArgs":true,"shell":false,"port":9399} {"metadata":{"emulator":{"name":"dataconnect"},"message":"Starting Data Connect Emulator with command {\"binary\":\"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0\",\"args\":[\"--logtostderr\",\"-v=2\",\"dev\",\"--listen=localhost:50001\",\"--config_dir=/home/user/studio/dataconnect\",\"--enable_output_schema_extensions=true\",\"--enable_output_generated_sdk=true\"],\"optionalArgs\":[\"listen\",\"config_dir\",\"enable_output_schema_extensions\",\"enable_output_generated_sdk\"],\"joinArgs\":true,\"shell\":false,\"port\":9399}"}}
[info] i  dataconnect: Data Connect Emulator logging to dataconnect-debug.log {"metadata":{"emulator":{"name":"dataconnect"},"message":"Data Connect Emulator logging to dataconnect-debug.log"}}
[debug] [2025-09-21T02:20:32.993Z] I0921 02:20:32.832148   33082 load.go:31] Reloading schema and connectors...
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0921 02:20:32.832148   33082 load.go:31] Reloading schema and connectors...\n"}}
[debug] [2025-09-21T02:20:33.296Z] W0921 02:20:33.266195   33082 control.go:68] [/emulator/studio 5533] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0921 02:20:33.266382   33082 control.go:94] [/emulator/studio 5533] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
E0921 02:20:33.274981   33082 load.go:73] Could not load sources: 
Errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data
I0921 02:20:33.281197   33082 collector.go:107] schema extensions wrote into "/home/user/studio/dataconnect/.dataconnect/schema"
Generated sources: prelude.gql [73251B] main/input.gql [68752B] main/relation.gql [33941B] main/query.gql [7604B] main/mutation.gql [20515B] main/implicit.gql [3592B] 
I0921 02:20:33.281273   33082 load.go:74] Finished reloading
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0921 02:20:33.266195   33082 control.go:68] [/emulator/studio 5533] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0921 02:20:33.266382   33082 control.go:94] [/emulator/studio 5533] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \nE0921 02:20:33.274981   33082 load.go:73] Could not load sources: \nErrors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\nI0921 02:20:33.281197   33082 collector.go:107] schema extensions wrote into \"/home/user/studio/dataconnect/.dataconnect/schema\"\nGenerated sources: prelude.gql [73251B] main/input.gql [68752B] main/relation.gql [33941B] main/query.gql [7604B] main/mutation.gql [20515B] main/implicit.gql [3592B] \nI0921 02:20:33.281273   33082 load.go:74] Finished reloading\n"}}
[debug] [2025-09-21T02:20:33.509Z] I0921 02:20:33.336207   33082 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0921 02:20:33.336207   33082 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001\n"}}
[debug] [2025-09-21T02:20:34.219Z] I0921 02:20:34.218490   33082 engine.go:169] [/emulator/studio 5533] ExecuteGraphqlRead IntrospectionQuery: succeeded. 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0921 02:20:34.218490   33082 engine.go:169] [/emulator/studio 5533] ExecuteGraphqlRead IntrospectionQuery: succeeded. \n"}}
[error] [Firebase Plugin] requireAuth error: Could not refresh access token: Unsuccessful response status code. Request failed with status code 500
[debug] [2025-09-21T19:50:12.501Z] [Firebase Plugin] Activating Firebase extension.
[debug] [2025-09-21T19:50:21.837Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-09-21T19:50:21.839Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]
[debug] [2025-09-21T19:50:21.861Z] [Firebase Plugin] VSCode notification server listening on port 40001
[info] [Firebase Plugin] Starting Data Connect toolkit (version 2.13.0) on port 50001
[debug] [2025-09-21T19:50:25.271Z] W0921 19:50:25.266279    2399 control.go:68] [/emulator/studio 3b02] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0921 19:50:25.266494    2399 control.go:94] [/emulator/studio 3b02] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0921 19:50:25.266279    2399 control.go:68] [/emulator/studio 3b02] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0921 19:50:25.266494    2399 control.go:94] [/emulator/studio 3b02] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \n"}}
[debug] [2025-09-21T19:50:25.277Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2025-09-21T19:50:25.279Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: port"}}
[debug] [2025-09-21T19:50:25.280Z] Starting Data Connect Emulator with command {"binary":"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0","args":["--logtostderr","-v=2","dev","--listen=localhost:50001","--config_dir=/home/user/studio/dataconnect","--enable_output_schema_extensions=true","--enable_output_generated_sdk=true"],"optionalArgs":["listen","config_dir","enable_output_schema_extensions","enable_output_generated_sdk"],"joinArgs":true,"shell":false,"port":9399} {"metadata":{"emulator":{"name":"dataconnect"},"message":"Starting Data Connect Emulator with command {\"binary\":\"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0\",\"args\":[\"--logtostderr\",\"-v=2\",\"dev\",\"--listen=localhost:50001\",\"--config_dir=/home/user/studio/dataconnect\",\"--enable_output_schema_extensions=true\",\"--enable_output_generated_sdk=true\"],\"optionalArgs\":[\"listen\",\"config_dir\",\"enable_output_schema_extensions\",\"enable_output_generated_sdk\"],\"joinArgs\":true,\"shell\":false,\"port\":9399}"}}
[info] i  dataconnect: Data Connect Emulator logging to dataconnect-debug.log {"metadata":{"emulator":{"name":"dataconnect"},"message":"Data Connect Emulator logging to dataconnect-debug.log"}}
[debug] [2025-09-21T19:50:25.466Z] I0921 19:50:25.353886    2404 load.go:31] Reloading schema and connectors...
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0921 19:50:25.353886    2404 load.go:31] Reloading schema and connectors...\n"}}
[debug] [2025-09-21T19:50:26.082Z] W0921 19:50:25.716121    2404 control.go:68] [/emulator/studio 1ca9] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0921 19:50:25.716208    2404 control.go:94] [/emulator/studio 1ca9] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
E0921 19:50:25.731848    2404 load.go:73] Could not load sources: 
Errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data
I0921 19:50:25.734879    2404 collector.go:107] schema extensions wrote into "/home/user/studio/dataconnect/.dataconnect/schema"
Generated sources: main/mutation.gql [20515B] prelude.gql [73251B] main/implicit.gql [3592B] main/input.gql [68752B] main/relation.gql [33941B] main/query.gql [7604B] 
I0921 19:50:25.735542    2404 load.go:74] Finished reloading
I0921 19:50:25.755622    2404 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0921 19:50:25.716121    2404 control.go:68] [/emulator/studio 1ca9] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0921 19:50:25.716208    2404 control.go:94] [/emulator/studio 1ca9] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \nE0921 19:50:25.731848    2404 load.go:73] Could not load sources: \nErrors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\nI0921 19:50:25.734879    2404 collector.go:107] schema extensions wrote into \"/home/user/studio/dataconnect/.dataconnect/schema\"\nGenerated sources: main/mutation.gql [20515B] prelude.gql [73251B] main/implicit.gql [3592B] main/input.gql [68752B] main/relation.gql [33941B] main/query.gql [7604B] \nI0921 19:50:25.735542    2404 load.go:74] Finished reloading\nI0921 19:50:25.755622    2404 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001\n"}}
[debug] [2025-09-21T19:50:27.105Z] I0921 19:50:27.102624    2404 engine.go:169] [/emulator/studio 1ca9] ExecuteGraphqlRead IntrospectionQuery: succeeded. 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0921 19:50:27.102624    2404 engine.go:169] [/emulator/studio 1ca9] ExecuteGraphqlRead IntrospectionQuery: succeeded. \n"}}
[error] [Firebase Plugin] requireAuth error: Could not refresh access token: Unsuccessful response status code. Request failed with status code 500
[info] [Firebase Plugin] Stopping Data Connect toolkit
[warn] ⚠  Data Connect Emulator has exited upon receiving signal: SIGINT 
[debug] [2025-09-21T23:54:45.527Z] [Firebase Plugin] Activating Firebase extension.
[debug] [2025-09-21T23:55:32.444Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-09-21T23:55:32.453Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]
[debug] [2025-09-21T23:55:32.514Z] [Firebase Plugin] VSCode notification server listening on port 40001
[info] [Firebase Plugin] Starting Data Connect toolkit (version 2.13.0) on port 50001
[debug] [2025-09-21T23:55:40.244Z] W0921 23:55:40.238629   21698 control.go:68] [/emulator/studio 5123] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0921 23:55:40.238761   21698 control.go:94] [/emulator/studio 5123] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0921 23:55:40.238629   21698 control.go:68] [/emulator/studio 5123] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0921 23:55:40.238761   21698 control.go:94] [/emulator/studio 5123] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \n"}}
[debug] [2025-09-21T23:55:40.248Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2025-09-21T23:55:40.251Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: port"}}
[debug] [2025-09-21T23:55:40.254Z] Starting Data Connect Emulator with command {"binary":"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0","args":["--logtostderr","-v=2","dev","--listen=localhost:50001","--config_dir=/home/user/studio/dataconnect","--enable_output_schema_extensions=true","--enable_output_generated_sdk=true"],"optionalArgs":["listen","config_dir","enable_output_schema_extensions","enable_output_generated_sdk"],"joinArgs":true,"shell":false,"port":9399} {"metadata":{"emulator":{"name":"dataconnect"},"message":"Starting Data Connect Emulator with command {\"binary\":\"/home/user/.cache/firebase/emulators/dataconnect-emulator-2.13.0\",\"args\":[\"--logtostderr\",\"-v=2\",\"dev\",\"--listen=localhost:50001\",\"--config_dir=/home/user/studio/dataconnect\",\"--enable_output_schema_extensions=true\",\"--enable_output_generated_sdk=true\"],\"optionalArgs\":[\"listen\",\"config_dir\",\"enable_output_schema_extensions\",\"enable_output_generated_sdk\"],\"joinArgs\":true,\"shell\":false,\"port\":9399}"}}
[info] i  dataconnect: Data Connect Emulator logging to dataconnect-debug.log {"metadata":{"emulator":{"name":"dataconnect"},"message":"Data Connect Emulator logging to dataconnect-debug.log"}}
[debug] [2025-09-21T23:55:40.522Z] I0921 23:55:40.435041   21703 load.go:31] Reloading schema and connectors...
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0921 23:55:40.435041   21703 load.go:31] Reloading schema and connectors...\n"}}
[debug] [2025-09-21T23:55:40.879Z] W0921 23:55:40.819449   21703 control.go:68] [/emulator/studio 536a] connector "example" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data

sources: example/queries.gql [530B] 
I0921 23:55:40.819534   21703 control.go:94] [/emulator/studio 536a] UpdateResources(): done
Schema: sources: schema/schema.gql [1207B] 
Connector "example": sources: example/queries.gql [530B] 
E0921 23:55:40.858878   21703 load.go:73] Could not load sources: 
Errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"W0921 23:55:40.819449   21703 control.go:68] [/emulator/studio 536a] connector \"example\" has errors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n\nsources: example/queries.gql [530B] \nI0921 23:55:40.819534   21703 control.go:94] [/emulator/studio 536a] UpdateResources(): done\nSchema: sources: schema/schema.gql [1207B] \nConnector \"example\": sources: example/queries.gql [530B] \nE0921 23:55:40.858878   21703 load.go:73] Could not load sources: \nErrors: example/queries.gql:2:3: mutation.InsertOrganization.organization_insert (data: Organization_Data): column createdAt is required but is missing in data\n"}}
[debug] [2025-09-21T23:55:40.949Z] I0921 23:55:40.883638   21703 collector.go:107] schema extensions wrote into "/home/user/studio/dataconnect/.dataconnect/schema"
Generated sources: main/relation.gql [33941B] main/query.gql [7604B] main/mutation.gql [20515B] prelude.gql [73251B] main/implicit.gql [3592B] main/input.gql [68752B] 
I0921 23:55:40.883716   21703 load.go:74] Finished reloading
I0921 23:55:40.927631   21703 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0921 23:55:40.883638   21703 collector.go:107] schema extensions wrote into \"/home/user/studio/dataconnect/.dataconnect/schema\"\nGenerated sources: main/relation.gql [33941B] main/query.gql [7604B] main/mutation.gql [20515B] prelude.gql [73251B] main/implicit.gql [3592B] main/input.gql [68752B] \nI0921 23:55:40.883716   21703 load.go:74] Finished reloading\nI0921 23:55:40.927631   21703 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001\n"}}
[debug] [2025-09-21T23:55:41.641Z] I0921 23:55:41.565447   21703 engine.go:169] [/emulator/studio 536a] ExecuteGraphqlRead IntrospectionQuery: succeeded. 
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0921 23:55:41.565447   21703 engine.go:169] [/emulator/studio 536a] ExecuteGraphqlRead IntrospectionQuery: succeeded. \n"}}
[error] [Firebase Plugin] requireAuth error: Could not refresh access token: Unsuccessful response status code. Request failed with status code 500
